#! /usr/bin/env bash

# also, to facilitate deployment to s3 on push, add a shell script to
# .git/hooks/pre-push containing:
# ./deploy-to-s3

echo "pushing to S3..."
dotclean.js .
aws s3 sync --profile "brettonw-iR" . s3://drone-website-bucket --delete --exclude "*" --include "texture/*" --include "plot-svg/*" --include "model/*" --include "js/*" --include "*.html" --acl public-read

echo "invalidating distribution to force cache refresh...";
aws cloudfront create-invalidation --profile "brettonw-iR" --distribution-id E2U7KZRBJDQVPS --paths "/*"
